### PR TITLE
Generate stub for leap

### LINKED ISSUE #11: New exercise: Leap
I'd like to generate this exercise, which is a very simple exercise about boolean logic.

Doing a simple search/replace into the HelloWorld test, I get the following:

```chapel
proc test_something(test : borrowed Test) throws {
  test.assertEqual(is_leap_year(2015), false);
}
```

Do you use `assertEqual` to test true and false, or is there a different test method?

What would the idiomatic name be for the function under test? (here: `is_leap_year`)

Are there any other changes you'd want to make?

### PR DESCRIPTION
**Pull request by kytrinyx**
Here's another generated draft. Let me know what needs to change in order to be idiomatic chapel.

Closes #11

### CODE REVIEW

**Comment by lucaferranti** [comment]
except for the two small comments I left in #14 looks good (title -> name in config.json and indentation in the stub and reference) looks good.

I think it would be more idiomatic to call the function `isLeapYear`, but maybe that's something fixed in the metadata that cannot be changed?

**Comment by lucaferranti** [comment]
do you want to play with your new Chapel installation and try writing the reference solution? 😄 

This could be a good first one if you are interested in chapel and want to play with it. Otherwise, just let me know and I'll push the reference solution

**Comment by kytrinyx** [comment]
> do you want to play with your new Chapel installation and try writing the reference solution?

I do! :-D

**Comment by kytrinyx** [comment]
> I think it would be more idiomatic to call the function isLeapYear, but maybe that's something fixed in the metadata that cannot be changed?

Most languages have different conventions, and we definitely always want to follow conventions. (E.g. in Ruby a predicate method would be called `leap_year?`)

I actually want to fix the metadata to make the default isLeapYear, because that's sort of the convention that we've generally followed in the specs, but it's a bit of a hassle so I've just put it on a list for a rainy day for now.

**Comment by kytrinyx** [comment]
Okay, this seems to be passing the tests, but the reference solution is almost certainly not idiomatic :)

**Review by lucaferranti — APPROVED** [review]
your solution looks good to me!

you could write `year % 100 != 0` instead of `!(year % 100 == 0)` but I guess this is more a matter of taste.

If you like golfing, one can also write `!( year % 4)` instead of `year % 4 == 0`, but personally I prefer your way of writing, because I find it easier to read

**Comment by kytrinyx** [comment]
> you could write year % 100 != 0 instead of !(year % 100 == 0) but I guess this is more a matter of taste.

It's funny. If I had been writing in a language I was familiar with I would have written `year % 100 != 0`, but because I was reading docs and just generally not in my comfort zone I ended up doing the other thing. I'm going to switch it around.

**Comment by kytrinyx** [comment]
> personally I prefer your way of writing, because I find it easier to read

Yeah, I prefer that way as well. Since we're the authors, we get to decide! Let's stick with this.

**Pull request merged**
