### PR TITLE
Implement stub for diamond

### PR DESCRIPTION
**Pull request by kytrinyx**
It might be worth extracting the expected result into a variable for readability. If so, would you confirm that the variable assignment should look like this?

```
var variableName = ["the", "data"];
```

Here are some reference solutions from other tracks:
- https://github.com/exercism/csharp/blob/main/exercises/practice/diamond/.meta/Example.cs
- https://github.com/exercism/elixir/blob/main/exercises/practice/diamond/.meta/example.ex
- https://github.com/exercism/go/blob/main/exercises/practice/diamond/.meta/example.go

### CODE REVIEW

**Comment by lucaferranti** [comment]
> `var variableName = ["the", "data"];`

yep, this defines an array of strings. We could print the ground truth

**Comment by kytrinyx** [comment]
I rebased onto main to get rid of the merge conflict on `config.json`, and regenerated the test suite with the extracted expectation. I named it `expected`, but if you have a better name based on Chapel conventions let me know and I'll regenerate it.

**Comment by lucaferranti** [comment]
>  I named it expected

that's exactly what I'd have called it ;)

**Comment by kytrinyx** [comment]
Hm. Tests are failing with:

```
TESTING practice/diamond/ 
====================
compilation failed for tests.chpl
Skipping registry update since no dependency found in manifest file.
test/tests.chpl:6: In function 'testDegenerateCaseWithASingleARow':
test/tests.chpl:8: error: unresolved call 'rows("A")'
test/tests.chpl:8: note: because no functions named rows found in scope
```

Let's just skip that test. It doesn't make sense in Chapel to have a different type for an incoming argument.

**Comment by kytrinyx** [comment]
Wait, I think I'm mis-reading the error message. Why is the call unresolved?

**Comment by kytrinyx** [comment]
The `tests.tmpl` is not compiling, but it's not compiling because the example solution is still missing, right? I haven't made a typo of sorts that is causing a syntax error?

**Comment by lucaferranti** [comment]
> test/tests.chpl:8: error: unresolved call 'rows("A")'
test/tests.chpl:8: note: because no functions named rows found in scope

yes, this is saying the function is not defined yet, which is detected already at compile time.

**Comment by kytrinyx** [comment]
It looks great! Ship it :)

**Review by lucaferranti — APPROVED** [review]

**Pull request merged**
