### PR TITLE
Implement stub for allergies

### PR DESCRIPTION
**Pull request by kytrinyx**
This one also seems like the test suite might be fine.

Here are some sample implementations:
- https://github.com/exercism/csharp/blob/main/exercises/practice/allergies/.meta/Example.cs
- https://github.com/exercism/ruby/blob/main/exercises/practice/allergies/.meta/example.rb
- https://github.com/exercism/go/blob/main/exercises/practice/allergies/.meta/example.go

### CODE REVIEW

**Comment by lucaferranti** [comment]
There were a few rough corners with this one, namely:

- the parser had a few issues, for the first function, it was parsed to `isAllergicTo("eggs")`, that is the score one was ignored
- for the second function it was displayed as `{{input}}`, which I guess is how it's displayed in the placeholder

I *think* one reason this one was harder to parse is that it had nested test cases (see the original json), for the tests I flattened them.

A few minor notices

- I changed the second function from `list` to `listAllergens`, because `list` felt a little to general
- a few test-functions were repeated, e.g. `testNotAllergicToAnything`, was 8 times (one for each ingredient). I disambiguated those into e.g. `testNotAllergicToAnythingEggs, testNotAllergicToAnythingChocolate` etc. The other alternative would have been to group all similar tests into one functionn, but then they would fail or pass as one.

**Comment by kytrinyx** [comment]
Ah, the `{{input}}` is my bad. I forgot to update the template to reflect the correct property.

For the test names, there should be a prefix; I might not have munged the JSON correctly.

I'll use your version to see if I can get the generator to generate (roughly) the right thing, as a sanity check on my logic.

**Comment by kytrinyx** [comment]
This looks great. You'll have to approve since I opened the PR.

**Review by lucaferranti — APPROVED** [review]

**Comment by kytrinyx** [comment]
I dug into what happened and it was mostly a problem with me having changed some things in the generator and forgotten to delete the old templates and regenerate them.

There was a problem, however, with the `assertEquals(something, [])` that needed to call `isEmpty()` instead.

Thanks for explaining what went wrong, as this gives me some concrete ideas about things I need to think about further!

**Pull request merged**
