### PR TITLE
add first exercise

### LINKED ISSUE #3: Implement Hello World exercise
I've added some notes for you to follow once you're ready to implement the first exercise (https://exercism.org/docs/building/tracks/new/add-first-exercise)

If these notes work and are helpful, let me know and I'll update the official documentation with them. If not please holler so we can figure out what's missing!

You can get the basics for the exercise in place by doing the following:

```
bin/fetch-configlet
```

Then you'll need to add some bits and pieces to the config.json in the "exercises.practice" array
```

      {
        "slug": "hello-world",
        "name": "Hello World",
        "uuid": "",
        "practices": [],
        "prerequisites": [],
        "difficulty": 1,
        "topics": []
      }
```

And then add the output from the following command to the uuid field for hello-world:

```
bin/configlet uuid
```

Then run the sync command:

```
bin/configlet sync --update --docs --metadata --tests
```

Next, add your GitHub username to "authors" in `exercises/practice/hello-world/.meta/config.json` (no "@" or anything).

Next you'll need to create the following in the `exercise/practice/hello-world` directory:
- a test suite with a single test ("the tests")
- a full solution with the text "Goodbye, Mars!" instead of the text "Hello, World!", causing the test to fail. ("the stub")
- a full, correct solution ("the example solution")

To do so you'll have to decide what the file paths are going to look like for the exercise. Ideally, you'll have filenames and paths that are idiomatic for the language. That said, if there's not a fairly strict requirement/expectation, prefer a shallower file structure (maybe even no subdirectories).

The example solution will go in the `.meta/` directory of the exercise, and you can name it anything. `example` is a common choice for the basename.

Once you have created the files you'll need to update the `exercises/practice/hello-world/.meta/config.json` file to have those paths.

### PR DESCRIPTION
**Pull request by lucaferranti**
fixes #3

### CODE REVIEW

**Comment by lucaferranti** [comment]
Hi @kytrinyx 👋 ,

I added the first exercise. Don't worry, I will not bother you for every single PR, but since this is the first one, could you check I did everything correctly, so that I can proceed smoothly with the other exercises.

In this PR,

- I filled the `config.json` in the root directory
- I added the hello world exercise.

Next (possibly in a separate PR), I would like to set the CI. If I understand correctly, `bin/test` runs the test, but using the example/exemplar file under `.meta` instead of the solution one. My question is, how can I teach `bin/test` to run the tests in the language specific way? Do you have any pointers to the relevant parts of the docs?

best
Luca

**Review by kytrinyx — APPROVED** [review]
This looks excellent!

**Comment by kytrinyx** [comment]
Yeah, CI is a great next step.

You don't have to use the `bin/test` script. You can use whatever command or script you would usually use, just replace the `bin/test` bit in the workflow file.

E.g. in Ruby the command is `bundle exec rake test` which executes a custom test script, whereas in Go it runs two scripts: https://github.com/exercism/go/blob/c1941fec21bad89ab83ee931f43d85e7fea63a03/.github/workflows/exercise-tests.yml#L45-L47 )

One way to approach this is to copy the files you need to a temporary directory, run the tests there, and then delete the directory when you're done. So for hello-world you'd copy the hello-world.chpl file from the base exercise directory, and the example.chpl file from the .meta directory to a temporary directory, along with whatever supporting files you need.

@ErikSchierboom Do you have any other suggestions for how to approach CI?

**Comment by lucaferranti** [comment]
Thank you very much for checking the PR. I opened #5 which has a quick and dirty bash script, I tested locally and it seems to work. If you have feedback/suggestions, very much appreciated :) I'll also have a look tomorrow at other repos and what they do

**Comment by kytrinyx** [comment]
I am a huge fan of quick and dirty bash scripts :) They enable progress and then at a later date some concrete pain or frustration leads us to improve it, and at that point we generally know enough to make good choices.

**Comment by ErikSchierboom** [comment]
The quick bash script looks like a good solution to me!

**Pull request merged**
