### PR TITLE
Implement stub for darts

### PR DESCRIPTION
**Pull request by kytrinyx**
Here are some reference implementations in other languages:

- https://github.com/exercism/csharp/blob/main/exercises/practice/darts/.meta/Example.cs
- https://github.com/exercism/ruby/blob/main/exercises/practice/darts/.meta/example.rb
- https://github.com/exercism/go/blob/main/exercises/practice/darts/.meta/example.go

### CODE REVIEW

**Review by lucaferranti — APPROVED** [review]
stub looks good and just added reference solution

**Comment by kytrinyx** [comment]
Nice, this looks great! I recommend using the `squash and merge` option in general when merging things that have multiple commits, as this gives us a nice link back to the PR in the merge commit on GitHub and has turned out to be much handier than I ever expected it to be. (In general this is our soft recommendation / soft preference on Exercism repositories).

**Comment by lucaferranti** [comment]
>  I recommend using the squash and merge option in general when merging things that have multiple commits

That's indeed what I've been doing, I also prefer "squash and merge"

I cannot edit the repo settings, but I wouldn't oppose setting there to always require "squash and merge".

**Comment by kytrinyx** [comment]
I shall make it so :)

**Pull request merged**
