### PR TITLE
enable runner

### LINKED ISSUE #38: Implement tooling
repo created at https://github.com/exercism/chapel-test-runner and being worked out

### PR DESCRIPTION
**Pull request by lucaferranti**
Closes: #38

### CODE REVIEW

**Comment by lucaferranti** [comment]
mmm if I start mess-up one-line PRs, maybe I should call it a day for now :sleeping:

**Comment by ErikSchierboom** [comment]
@lucaferranti You'll need to add a `test_runner.average_run_time` field that estimates the amount of time the test runner takes (as an integer representing seconds). See https://exercism.org/docs/building/tracks/config-json#h-metadata
Judging by the speed running the tests of the test runner locally, it should probably be set to about `10` or so.

FYI I've opened a PR that we need to merge to allow deploying the test runner to production: https://github.com/exercism/terraform/pull/109

**Comment by lucaferranti** [comment]
cool, I've set the average time. Just double-checking this is indeed **average** time, not maximum time threshold to timeout? Anyway, once the test-runner is deployed, I can test on the website an exercise wiht a lot of tests and see if it causes problems

**Comment by ErikSchierboom** [comment]
It is indeed average run time (it's just there for the progress bar than is shown when submitting)

**Comment by lucaferranti** [comment]
@ErikSchierboom fixed the missing field. Let me know if anything else is missing

**Review by ErikSchierboom — APPROVED** [review]
I was just waiting for https://github.com/exercism/chapel-test-runner/actions/runs/8108679698/job/22331495097 to finish. We're good!

**Pull request merged**
